replicaCount: 1

image:
  repository: krishc145/simple-java-ms
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}
